### ISSUE TITLE
Fails to launch on KDE wayland

### ISSUE THREAD

**Issue by CorneliusCornbread** [ardaku/alloy#170]
Both using `cargo install emulsion` and building from source give the following error on running.

```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
[1]    81565 IOT instruction (core dumped)  cargo run
```

No panic file is made

**Comment by AldaronLau** [comment]
@CorneliusCornbread Thanks for opening the issue.  I'm guessing this is because of running an older winit ~(I tried updating it, but had some issues on my system)~ **edit**: I may have misremembered this, might have been a glium/glutin issue.

~I have some bigger planned changes that I believe should resolve this, but before I can do that I'll need to swap out the glium dependency for wgpu.~

**Comment by AldaronLau** [comment]
I decided to test again (since it's been a while), and it looks like the winit issue has been resolved - so I updated it.  @CorneliusCornbread Do you want to try building from source again?

**Comment by CorneliusCornbread** [comment]
> I decided to test again (since it's been a while), and it looks like the winit issue has been resolved - so I updated it. @CorneliusCornbread Do you want to try building from source again?

Still having the same issue when building from source. Are the changes you made to winit on a separate branch or was it only a version change for winit?

**Comment by CorneliusCornbread** [comment]
Upon further testing it seems to be an issue with glium being out of date. Upgrading to 0.31.0 resolves the problem while avoiding breaking API changes. 0.32 has breaking API changes

**Comment by AldaronLau** [comment]
> Still having the same issue when building from source. Are the changes you made to winit on a separate branch or was it only a version change for winit?

I did it on the `stable` branch.

> Upon further testing it seems to be an issue with glium being out of date. Upgrading to 0.31.0 resolves the problem while avoiding breaking API changes. 0.32 has breaking API changes

It was still having weird rendering artifacts on 0.31.0, but 0.32.0 worked for my system so I updated it (although it's not rendering the titlebar quite right - wasn't before the update either, though, workable for now).  Do you mind testing the `stable` branch again to make sure it didn't re-break (seems unlikely, but good to check)?

**Comment by CorneliusCornbread** [comment]
> > Still having the same issue when building from source. Are the changes you made to winit on a separate branch or was it only a version change for winit?
> 
> I did it on the `stable` branch.
> 
> > Upon further testing it seems to be an issue with glium being out of date. Upgrading to 0.31.0 resolves the problem while avoiding breaking API changes. 0.32 has breaking API changes
> 
> It was still having weird rendering artifacts on 0.31.0, but 0.32.0 worked for my system so I updated it (although it's not rendering the titlebar quite right - wasn't before the update either, though, workable for now). Do you mind testing the `stable` branch again to make sure it didn't re-break (seems unlikely, but good to check)?

Just tested your changes, it's working just fine for me now. The title bar renders mostly fine for me other than the icon, though that's common for wayland applications to not have working in my experience.
